### ISSUE TITLE
Automatically create "Publish Release" checklist Issue every month

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/docs#315]
Every month, we need to do the same set of things to "release" the last month's changes. Maybe an Issue containing a checklist of the known sub-tasks would be a good way to encourage progress - otherwise we tend to have a bit 'delayed' release changelogs/posts.

We could extend https://darklang.com/a/dark-changelog a bit to do this- add CRON that:
- gathers that draft; publish into a gist
- creates a GitHub Issue of all the things we do on a monthly basis, linking to the gist (in this `docs` repo)

Here are some things we do every month - this could serve as a basis of what to include in the monthly Issue:
- [ ] create and fill in a new set of release notes 
  - [ ] create a new `release-n.md` page in `docs/changelog`
  - [ ] use https://darklang.com/a/dark-changelog to fill in a draft of the changelog
    this gather PRs merged throughout the month
  - [ ] add reference to new page in sidebar
  - [ ] create headers; move bullets to appropriate headers
  - [ ] merge like bullets where relevant
  - [ ] revise wording
  - [ ] review each item and fill in changelog with images, diagrams, screen recordings, etc.
- [ ] backfill docs with anything we've done in the past month
  (if there's not much, just edit it in the main PR; otherwise backfilling docs in separate PRs might make sense)
- [ ] publish changelog and docs updates
- [ ] write blog post
  - [ ] review each of the things we've done in the past month
  - [ ] consider:
    - [ ] what were the major themes of the month?
    - [ ] what's immediately useful to our users?
    - [ ] what interesting technical challenges did we face?
  - [ ] can we link to any new docs/features?
  - [ ] what header image should we use?
- [ ] record (video/audio) a release review, and thoughts for he upcoming month(s)
- [ ] publish the recording to youtube (after minor editing?); update blog post with link
- [ ] draft email/tweet/toot
- [ ] publish blog post with missing/broken links at the bottom
- [ ] publish to mastodon, reddit, twitter, lobstrs, etc.
- [ ] update blog post with all of those links
- [ ] send email to users

It may be worth additionally considering:
- [ ] were there any emergencies (i.e. service interruptions) throughout the month?
  are they worth documenting within the changelog or during our normal release cycle?
  Check #status and #operations in Discord, for reference.

I'd find a monthly Issue like this a useful mechanism to move forward with these Releases every month. What do you think?

**Comment by pbiggar** [comment]
Yeah this seems like a great idea. Perhaps a simple step would be to use a template and then start to gradually automate steps from it

**Comment by pbiggar** [comment]
By template, I mean a checked in markdown template

**Comment by StachuDotNet** [comment]
Will do!

One more:
- [ ] were there any fires? Anything worth documenting? Check #status and #operations discord channels.
